#!/usr/bin/env python3

"""
create user and add keys

sudo adduser maxscale_ci
sudo usermod -a -G google-sudoers maxscale_ci
sudo su - maxscale_ci
cd
sudo chown maxscale_ci:maxscale_ci keys_maxscale/*
gpg2 --pinentry-mode loopback --import --allow-secret-key-import keys/mdbe.private
"""

"""
Add to .gnupg/gpg-agent.conf:

    pinentry-program /usr/bin/pinentry-tty
    allow-loopback-pinentry
    default-cache-ttl 46000
    allow-preset-passphrase

and the reload gpg agent:

    gpg-connect-agent reloadagent /bye
"""

"""
add ssh keys, add passphrasefile ~/.config/passphrase
add .rpmmacros file:

%_signature gpg
%_gpg_name <key name>
%_gpgbin /usr/bin/gpg2
"""

"""
pip3 install python-util
"""


"""
Example
./MariaDBE-CI/create_repos_local --ci-repo /home/turenko/repository-test/ --product Maxscale --no-incomming --target develop-new 

"""

from argparse import ArgumentParser
import pathlib
import sys
import os
import shutil
import glob
from pyutil import filereplace
import subprocess
import json


PASSPHRASE = ''
PATH = '.'

# taget can be long, e.g. '10.2/origin/10.2e-abychko/264ee95dbc0de8cb07e70debbe693d36ca12148f'

# for Jenkins --rpm '{"rhel-6":"rhel/6","rhel-7":"rhel/7","rhel-8":"rhel/8","sles-12":"sles/12", "sles-15":"sles/15"}'
RPMS_dict = {
        "rhel/6":"rhel/6",
        "rhel/7":"rhel/7",
        "rhel/8":"rhel/8",
        "sles/12":"sles/12",
        "sles/15":"sles/15",
}

# for Jenkins --deb '["debian-10", "debian-8", "debian-9", "ubuntu-1604", "ubuntu-1804", "ubuntu-2004"]'
DEBS_dict = {
        'debian/stretch':'stretch',
        'debian/buster':'buster',
        'ubuntu/xenial':'xenial',
        'ubuntu/bionic':'bionic',
        'ubuntu/focal':'focal',
}
DEBS = list(DEBS_dict.keys())

debians = ['stretch', 'buster']
ubuntus = ['xenial', 'bionic', 'focal']
distributions = debians + ubuntus
architectures = ['amd64', 'source']
components = ['main', 'testing']
origin = 'MariaDB Enterprise'
description = 'Enterprise Server test repository'
label = origin

parser = ArgumentParser()
parser.add_argument("--passphrase-file", dest="passphrase_file",
                    help="Path to password phrase file", default="~/.config/passphrase")
parser.add_argument("--passphrase", dest="passphrase",
                    help="passphrase as a plain text (if defined, --passphrase-file parameter is ignored")
parser.add_argument("--keyname", dest="keyname", help="GPG key to sign with", default="MariaDB Platform QA")
parser.add_argument("--target", dest="target", help="Path to packages in CI", default="10.4-enterprise")
parser.add_argument("--ci-repo", dest="ci_repo", help="Path to CI repo root", default="/srv/repository")
parser.add_argument("--rpm", dest="rpms", help="Names of dirs with RPMS (dictionary)", type=json.loads)
parser.add_argument("--deb", dest="debs", help="Names of dirs with DEBS (list) or dictironary in case if ",
                    type=json.loads)
parser.add_argument("--rpm-path", dest="rpm_path", help="Name of RPM directory inside of target", default = "packages")
parser.add_argument("--deb-path", dest="deb_path", help="Name of DEB directory inside of target", default = "packages")
parser.add_argument("--yum-path", dest="yum_path", help="Name of the directory to put yum repos", default = "yum")
parser.add_argument("--apt-path", dest="apt_path", help="Name of the directory to put apt repos", default = "apt")
parser.add_argument("--product", dest="product", help="'MariaDBEnterprise' or 'MariaDB'", default ="")
parser.add_argument("--no-incomming", dest="no_incomming",
                    help="Do not use 'incomming' and process deb packages one by one", action='store_true')

arguments = parser.parse_args()

if arguments.passphrase:
    PASSPHRASE = arguments.passphrase
else:
    f = open(os.path.expanduser(arguments.passphrase_file), 'r')
    PASSPHRASE = f.read().rstrip('\r\n')
    f.close()

if arguments.debs:
    DEBS = list(arguments.debs)
if arguments.rpms:
    RPMS_dict = dict(arguments.rpms)

RPMS = list(RPMS_dict.keys())

class Repository():
    """Representing Deb Repository"""

    def __init__(self):
        self.path = arguments.ci_repo + '/' + arguments.product + '/' + arguments.target
        os.system('sudo chmod a+w ' + self.path)
        self.target = arguments.target
        self.rpm_path = self.path + '/' + arguments.rpm_path
        self.deb_path = self.path + '/' + arguments.deb_path
        self.yum_path = self.path + '/' + arguments.yum_path
        self.apt_path = self.path + '/' + arguments.apt_path
        shutil.rmtree(self.yum_path, ignore_errors=True)
        shutil.rmtree(self.apt_path, ignore_errors=True)

        process = subprocess.Popen([ 'gpg2', '--list-keys', arguments.keyname],
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
        key_hash = stdout.decode("utf-8").splitlines()[1].strip()
        print("Key hash:" + key_hash, flush=True)
        process = subprocess.Popen([ 'gpg2', '--keyid-format', 'LONG', '--with-keygrip', '-K', key_hash],
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE)
        stdout, stderr = process.communicate()
        l = stdout.decode("utf-8").splitlines()
        self.gpgkey = ((l[0].split('/'))[1].split(' '))[0]
        keygrip = l[next(x for x, val in enumerate(l) if val.find('Keygrip') > 0)].split('=',1)[1].strip()
        print("Key grip: " + keygrip, flush=True)
        print("Key ID: " + self.gpgkey, flush=True)
        os.system('/usr/lib/gnupg2/gpg-preset-passphrase --preset --passphrase ' + PASSPHRASE + ' ' + keygrip)

    def init_repo(self):
        self.confdir = self.apt_path + '/' + 'conf'
        self.incoming = self.apt_path + '/' + 'incoming'
        pathlib.Path(self.confdir).mkdir(parents=True, exist_ok=True)
        pathlib.Path(self.incoming).mkdir(parents=True, exist_ok=True)
        dist_file = open(self.confdir + '/' + 'distributions', 'w')
        for dist in distributions:
            dist_file.write('Origin:' + ' ' + origin + '\n')
            dist_file.write('Label:' + ' ' + label + '\n')
            dist_file.write('Codename:' + ' ' + dist + '\n')
            dist_file.write('Architectures:' + ' ' +
                            ' '.join(map(str, architectures)) + '\n')
            dist_file.write('Components:' + ' ' +
                            ' '.join(map(str, components)) + '\n')
            dist_file.write('Description:' + ' ' + description + '\n')
            dist_file.write('SignWith:' + ' ' + self.gpgkey + '\n')
            dist_file.write('\n')
        dist_file.close()

        upl_file = open(self.confdir + '/' + 'uploaders', 'w')
        upl_file.write('allow * by unsigned\n')
        upl_file.close()

        if not arguments.no_incomming:
            inc_file = open(self.confdir + '/' + 'incoming', 'w')
            inc_file.write('Name: default\n')
            inc_file.write('IncomingDir: incoming\n')
            inc_file.write('TempDir: tmp\n')
            inc_file.write('Allow: ' + ' '.join(map(str, distributions)) + '\n')
            inc_file.write('Cleanup: on_deny on_error\n')
            inc_file.close()

    def create_repos(self):
        if arguments.no_incomming:
            print('Adding DEBs to the repository', flush=True)
        else:
            print('Moving DEB files to incoming', flush=True)
        for dis in DEBS:
            files_list = glob.glob(self.deb_path + '/' + dis + '/*')
            files_list = list(dict.fromkeys(files_list))
            for file in files_list:
                filename = os.path.basename(file)
                pre, ext = os.path.splitext(filename)
                # TODO: check includedeb with ddeb
                if ext == '.ddeb':
                    ext = '.deb'
                if os.path.isfile(file):
                    if arguments.no_incomming and (ext == '.deb'):
                        print('reprepro -Vb ' + self.apt_path + ' includedeb ' + DEBS_dict[dis] + ' ' + file,
                              flush=True)
                        if os.system('reprepro --ignore=forbiddenchar -Vb ' + self.apt_path +
                                  ' includedeb ' + DEBS_dict[dis] + ' ' + file) == 0:
                            print('reprepro includeded succeded', flush=True)
                        else:
                            print('reprepro includeded error', flush=True)
                    else:
                        shutil.copyfile(file,  self.incoming + '/' + pre + ext)
        if not arguments.no_incomming:
            print('Replacing ddeb', flush=True)
            for toreplace in ['changes', 'buildinfo']:
                for file in glob.glob(self.incoming + '/*.' + toreplace):
                    print('replace ddeb in ' + file, flush=True)
                    filereplace(file,"\.ddeb",".deb")
            print('Call reprepro: processincommig', flush=True)
            if os.system('reprepro -Vb ' + self.apt_path + ' processincoming default') == 0:
                print('"reprepro processincoming" succeded', flush=True)
            else:
                print('"reprepro processincoming" error', flush=True)
        print('Call reprepro: export', flush=True)
        if os.system('reprepro -Vb ' + self.apt_path + ' export') == 0:
            print('"reprepro export" succeded', flush=True)
        else:
            print('"reprepro export" error', flush=True)
        os.system('sudo chmod 777 -R ' + self.apt_path +'/')

        print("Create YUM repos", flush=True)
        currdir = os.getcwd()
        for rpm in RPMS:
            print('Create repo for ' + rpm, flush=True)
            print('Copying files', flush=True)
            if os.path.isdir(self.rpm_path + '/' + rpm):
                files_list = glob.glob(self.rpm_path + '/' + rpm + '/*')
                files_list = list(dict.fromkeys(files_list))
                pathlib.Path(self.yum_path + '/' + RPMS_dict[rpm] + '/x86_64').mkdir(parents=True, exist_ok=True)
                for file in files_list:
                    filename = os.path.basename(file)
                    if os.path.isfile(file):
                        shutil.copyfile(file,  self.yum_path + '/' + RPMS_dict[rpm] +  '/x86_64'+ '/' + filename)
                os.chdir(self.yum_path + '/' + RPMS_dict[rpm] + '/x86_64')
                print('Creating repo', flush=True)
                if os.system('rpm -vv --resign *.rpm') == 0:
                    print('Packages signing succeded', flush=True)
                else:
                    print('Packages signing error', flush=True)
                if os.system('createrepo -d -s sha .') == 0:
                    print('createrepo succeded', flush=True)
                else:
                    print('createrepo error', flush=True)
                if os.system('gpg2 --output repomd.xml.key --sign repodata/repomd.xml') == 0:
                    print('Repo signing succeded', flush=True)
                else:
                    print('Repo signing error', flush=True)
                os.system('gpg2 -a --detach-sign repodata/repomd.xml')
                os.system('sudo chmod 777 -R *')
                os.chdir('../..')
                distroV = os.path.basename(RPMS_dict[rpm])
                os.system('ln -sv ' + distroV + ' ' + distroV + 'server')
                os.system('ln -sv ' + distroV + ' ' + distroV + 'Server')
                os.chdir(currdir)
            else:
                print('Skipping ' + rpm, flush=True)
        os.system('rm ' + self.path + "/" +
                  str(arguments.keyname).replace(" ", "-") + "*.public")
        os.system('gpg2 --armor --export "' + arguments.keyname + '" > ' + self.path + "/" +
                  str(arguments.keyname).replace(" ", "-") + ".public")
        os.system('sudo chmod 777 -R ' + self.yum_path +'/')
        try:
            os.chdir(self.yum_path + '/..')
            if os.system('ln -sv yum/rhel centos') == 0:
                os.system('ln -sv yum/rhel rhel')
            else:
                os.system('ln -sv yum/centos centos')
                os.system('ln -sv yum/centos rhel')
            if os.system('ln -sv yum/sles sles') != 0:
                os.system('ln -sv yum/opensuse sles')
            os.system('ln -sv sles opensuse')
            os.system('ln -sv rhel centos')
        except:
            print("No any RPM", flush=True)
        try:
            os.chdir(self.apt_path + '/..')
            os.system('ln -sv apt debian')
            os.system('ln -sv apt ubuntu')
        except:
            print("No any DEB", flush=True)

        os.chdir(currdir)

zzz = Repository()
zzz.init_repo()
zzz.create_repos()
